import type { User, Order, Address } from "@/types/users";
import { mockProducts } from "./mock-data";

export const mockUser: User = {
  id: "1",
  name: "Alex Johnson",
  email: "alex.johnson@example.com",
  avatar: "/professional-headshot.png",
  phone: "+1 (555) 123-4567",
  bio: "Sneaker enthusiast and runner. Always looking for the perfect pair.",
  memberSince: new Date("2023-01-15"),
};

export const mockOrders: Order[] = [
  {
    id: "1",
    orderNumber: "ORD-2024-001",
    date: new Date("2024-01-15"),
    status: "delivered",
    items: [
      {
        id: "1",
        product: mockProducts[0],
        variant: mockProducts[0].variants![0],
        quantity: 1,
        price: mockProducts[0].base_price,
      },
    ],
    subtotal: 129.99,
    shipping: 0,
    tax: 10.4,
    total: 140.39,
    shippingAddress: {
      id: "1",
      label: "Home",
      fullName: "Alex Johnson",
      street: "123 Main Street",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
      country: "United States",
      phone: "+1 (555) 123-4567",
      isDefault: true,
    },
  },
  {
    id: "2",
    orderNumber: "ORD-2024-002",
    date: new Date("2024-02-20"),
    status: "shipped",
    items: [
      {
        id: "2",
        product: mockProducts[1],
        variant: mockProducts[1].variants![0],
        quantity: 2,
        price: mockProducts[1].base_price,
      },
    ],
    subtotal: 199.98,
    shipping: 0,
    tax: 16.0,
    total: 215.98,
    shippingAddress: {
      id: "1",
      label: "Home",
      fullName: "Alex Johnson",
      street: "123 Main Street",
      city: "San Francisco",
      state: "CA",
      zipCode: "94102",
      country: "United States",
      phone: "+1 (555) 123-4567",
      isDefault: true,
    },
  },
  {
    id: "3",
    orderNumber: "ORD-2024-003",
    date: new Date("2024-03-10"),
    status: "processing",
    items: [
      {
        id: "3",
        product: mockProducts[2],
        variant: mockProducts[2].variants![0],
        quantity: 1,
        price: mockProducts[2].base_price,
      },
    ],
    subtotal: 149.99,
    shipping: 0,
    tax: 12.0,
    total: 161.99,
    shippingAddress: {
      id: "2",
      label: "Work",
      fullName: "Alex Johnson",
      street: "456 Market Street, Suite 200",
      city: "San Francisco",
      state: "CA",
      zipCode: "94103",
      country: "United States",
      phone: "+1 (555) 123-4567",
      isDefault: false,
    },
  },
];

export const mockAddresses: Address[] = [
  {
    id: "1",
    label: "Home",
    fullName: "Alex Johnson",
    street: "123 Main Street",
    city: "San Francisco",
    state: "CA",
    zipCode: "94102",
    country: "United States",
    phone: "+1 (555) 123-4567",
    isDefault: true,
  },
  {
    id: "2",
    label: "Work",
    fullName: "Alex Johnson",
    street: "456 Market Street, Suite 200",
    city: "San Francisco",
    state: "CA",
    zipCode: "94103",
    country: "United States",
    phone: "+1 (555) 987-6543",
    isDefault: false,
  },
];
